### ISSUE TITLE
jump list pollution

### ISSUE THREAD

**Issue by vbauerster** [alexherbo2/word-movement.kak#2]
I've noticed that every word movement saves itself into jump list with this plugin.
It's not so convenient, as jump list becomes very polluted.
Is it possible to introduce an option for user whether to save to jump list or not?

**Comment by alexherbo2** [comment]
How to prevent to save to the jump list.

**Comment by alexherbo2** [comment]
@vbauerster Please see https://github.com/alexherbo2/move-line.kak/issues/2#issuecomment-541417759 also.
